# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

##@ DR Spoke Management
# Usage: make onboard-spoke CLUSTER=<managedcluster-name>
#   Example: make onboard-spoke CLUSTER=ocp-dc12
#
# Pre-requisites (on the spoke, before running this):
#   - ODF installed with a CSI StorageClass set as the cluster default
#   - Cluster already imported into ACM (visible in `oc get managedcluster`)
#   - Hub secrets loaded (`make install` or `make load-secrets` already run)
#
# After running this, the full onboarding sequence is automatic (~15-25 min):
#   ACM PlacementRule matches → ArgoCD bootstrap → Trilio operator (OLM)
#   → ESO syncs secrets from Vault → TVM reconciles → BackupTarget Available
#   → wordpress-restore namespace provisioned → Trilio registers with hub Target

CLUSTER ?= $(error CLUSTER is required — run: make onboard-spoke CLUSTER=<name>)

.PHONY: onboard-spoke
onboard-spoke: ## Onboard a DR spoke cluster: make onboard-spoke CLUSTER=<managedcluster-name>
	@echo "Onboarding spoke cluster: $(CLUSTER)"
	@oc get managedcluster $(CLUSTER) > /dev/null 2>&1 || \
	  (echo "ERROR: ManagedCluster '$(CLUSTER)' not found. Import it into ACM first." && exit 1)
	@oc label managedcluster $(CLUSTER) clusterGroup=secondary --overwrite
	@echo "Label applied. ACM will now provision the full Trilio DR stack (~15-25 min)."
	@echo ""
	@echo "ACTION REQUIRED: The spoke app-of-apps has no automated sync."
	@echo "Switch to the SPOKE cluster context and run:"
	@echo "  oc patch application.argoproj.io main-trilio-continuous-restore-secondary -n openshift-gitops \\"
	@echo "    --type merge -p '{\"operation\":{\"sync\":{}}}'"
	@echo ""
	@echo "Monitor with: make spoke-status CLUSTER=$(CLUSTER)"

.PHONY: spoke-status
spoke-status: ## Check DR spoke onboarding and Continuous Restore status: make spoke-status CLUSTER=<name>
	@echo ""
	@echo "=== ACM ManagedCluster: $(CLUSTER) ==="
	@oc get managedcluster $(CLUSTER) --no-headers 2>/dev/null || echo "  Not found"
	@echo ""
	@echo "=== Hub Target: Registered CR Instances ==="
	@oc get target.triliovault.trilio.io trilio-s3-target -n trilio-system \
	  -o jsonpath='{.status.availableContinuousRestoreInstances}' 2>/dev/null \
	  | python3 -m json.tool 2>/dev/null || echo "  Target not available or no instances registered"
	@echo ""
	@echo "=== Hub E2E DR Status (trilio-dr-status ConfigMap) ==="
	@oc get configmap trilio-dr-status -n imperative \
	  -o jsonpath='{range .data}{@k}{"\n"}' 2>/dev/null || \
	  oc get configmap trilio-dr-status -n imperative -o yaml 2>/dev/null || \
	  echo "  ConfigMap not yet created (hub imperative job has not run)"
	@echo ""
	@echo "Spoke-side CR status (run on spoke context):"
	@echo "  oc get configmap trilio-cr-status -n imperative -o yaml"

.PHONY: unlabel-spoke
unlabel-spoke: ## Step 1 of offboard — remove ACM clusterGroup label (run on hub context): make unlabel-spoke CLUSTER=<name>
	@[ -n "$(CLUSTER)" ] || (echo "ERROR: CLUSTER is required. Usage: make unlabel-spoke CLUSTER=<name>" && exit 1)
	@echo "Removing clusterGroup label from ACM ManagedCluster: $(CLUSTER)"
	@oc get managedcluster $(CLUSTER) > /dev/null 2>&1 || \
	  (echo "ERROR: ManagedCluster '$(CLUSTER)' not found on this hub." && exit 1)
	@oc label managedcluster $(CLUSTER) clusterGroup-
	@echo "Done. Switch to spoke context and run: make offboard-spoke CLUSTER=$(CLUSTER)"

.PHONY: offboard-spoke
offboard-spoke: ## Step 2 of offboard — clean up spoke resources (run on spoke context): make offboard-spoke CLUSTER=<name>
	@[ -n "$(CLUSTER)" ] || (echo "ERROR: CLUSTER is required. Usage: make offboard-spoke CLUSTER=<name>" && exit 1)
	@echo "Offboarding spoke: $(CLUSTER)"
	@echo "Pre-requisite: 'make unlabel-spoke CLUSTER=$(CLUSTER)' must have been run on hub context first."
	@ansible-playbook ansible/playbooks/offboard-spoke.yaml \
	  -e spoke_cluster_name=$(CLUSTER)

.PHONY: offboard-hub
offboard-hub: ## Tear down the Trilio pattern from the hub cluster (run on hub context)
	@echo "Offboarding hub — this will remove all Trilio pattern resources."
	@echo "ACM, Vault, ESO, and OpenShift GitOps are NOT removed."
	@read -p "Continue? [y/N] " ans && [ "$$ans" = "y" ] || exit 0
	@ansible-playbook ansible/playbooks/offboard-hub.yaml

.PHONY: dr-status
dr-status: ## Show hub-side E2E DR status ConfigMap
	@oc get configmap trilio-dr-status -n imperative -o yaml 2>/dev/null || \
	  echo "ConfigMap trilio-dr-status not found in imperative namespace"

include Makefile-common
