apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  {{- if .Values.wordpress.route.host }}
  host: {{ .Values.wordpress.route.host }}
  {{- end }}
  to:
    kind: Service
    name: wordpress
  port:
    targetPort: 80
