apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
type: Opaque
data:
  password: {{ .Values.mysql.password | b64enc | quote }}
